-- AlterTable
ALTER TABLE `DailyAnalysis`
  ADD COLUMN `feedbackScore` INT NULL,
  ADD COLUMN `feedbackNote` TEXT NULL,
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
