import { AnalysisSignalCard } from '@web/entities/signal/analysis-signal-card';
import { AnalysisSignalDetailPanel } from '@web/entities/signal/analysis-signal-detail-panel';
import type { DashboardAnalysisRun, DashboardSignal } from '@web/shared/api/types';

type AnalysisFeedProps = Readonly<{
  signals: DashboardSignal[];
  analysisRunLookup: Record<string, DashboardAnalysisRun>;
  selectedSignal: DashboardSignal | null;
  selectedRun: DashboardAnalysisRun | null;
  latestCloseLabel: string;
}>;

export function AnalysisFeed({
  signals,
  analysisRunLookup,
  selectedSignal,
  selectedRun,
  latestCloseLabel
}: AnalysisFeedProps) {
  const selectedSignalId = selectedSignal?.id ?? null;

  return (
    <main className="dashboard-shell analysis-shell">
      <section className="hero-card analysis-hero">
        <div className="hero-copy">
          <p className="eyebrow">Analysis Feed</p>
          <h1>Structured Analysis Feed</h1>
          <p className="lead">
            Review signal cards generated by the worker and inspect the matching analysis run
            context in one place.
          </p>
        </div>
        <div className="hero-status">
          <span className="status-dot" />
          <span>Latest close {latestCloseLabel}</span>
        </div>
      </section>

      <section className="analysis-layout">
        <article className="panel">
          <h2>Signal Cards</h2>
          <p>Scan symbol, trend, bias, confidence, support, and resistance at a glance.</p>

          <div className="analysis-list">
            {signals.map((signal) => (
              <AnalysisSignalCard
                key={signal.id}
                signal={signal}
                analysisRun={analysisRunLookup[signal.analysisRunId]}
                selected={signal.id === selectedSignalId}
              />
            ))}
          </div>
        </article>

        <AnalysisSignalDetailPanel signal={selectedSignal} analysisRun={selectedRun} />
      </section>
    </main>
  );
}
