import { createApiClient } from '../../lib/api';
import { formatDateTime } from '../../lib/format';
import type { DashboardAnalysisRun, DashboardSignal } from '../../lib/types';
import { AnalysisCard } from '../../components/analysis/analysis-card';
import { AnalysisDetailPanel } from '../../components/analysis/analysis-detail-panel';

type AnalysisPageProps = Readonly<{
  searchParams?: {
    signal?: string | string[];
  };
}>;

async function loadAnalysisData() {
  const client = createApiClient();

  try {
    const [signals, analysisRuns] = await Promise.all([
      client.fetchSignals(),
      client.fetchAnalysisRuns()
    ]);

    return { signals, analysisRuns };
  } catch {
    return {
      signals: [] as DashboardSignal[],
      analysisRuns: [] as DashboardAnalysisRun[]
    };
  }
}

function pickSearchParam(searchParam?: string | string[]) {
  return Array.isArray(searchParam) ? searchParam[0] : searchParam;
}

function getAnalysisRunForSignal(
  signal: DashboardSignal,
  analysisRuns: DashboardAnalysisRun[]
): DashboardAnalysisRun | undefined {
  return analysisRuns.find((run) => run.id === signal.analysisRunId);
}

export default async function AnalysisPage({ searchParams }: AnalysisPageProps) {
  const { signals, analysisRuns } = await loadAnalysisData();
  const selectedSignalId = pickSearchParam(searchParams?.signal) ?? signals[0]?.id;
  const selectedSignal = signals.find((signal) => signal.id === selectedSignalId) ?? signals[0] ?? null;
  const selectedRun = selectedSignal ? getAnalysisRunForSignal(selectedSignal, analysisRuns) : null;
  const latestClose =
    analysisRuns[0]?.candleCloseTime instanceof Date
      ? formatDateTime(analysisRuns[0].candleCloseTime)
      : 'just now';

  return (
    <main className="dashboard-shell analysis-shell">
      <section className="hero-card analysis-hero">
        <div className="hero-copy">
          <p className="eyebrow">Analysis Feed</p>
          <h1>Structured Analysis Feed</h1>
          <p className="lead">
            Review signal cards generated by the worker and inspect the matching analysis run
            context in one place.
          </p>
        </div>
        <div className="hero-status">
          <span className="status-dot" />
          <span>Latest close {latestClose}</span>
        </div>
      </section>

      <section className="analysis-layout">
        <article className="panel">
          <h2>Signal Cards</h2>
          <p>Scan symbol, trend, bias, confidence, support, and resistance at a glance.</p>

          <div className="analysis-list">
            {signals.map((signal) => (
              <AnalysisCard
                key={signal.id}
                signal={signal}
                analysisRun={getAnalysisRunForSignal(signal, analysisRuns)}
                selected={signal.id === selectedSignalId}
              />
            ))}
          </div>
        </article>

        <AnalysisDetailPanel signal={selectedSignal} analysisRun={selectedRun ?? null} />
      </section>
    </main>
  );
}
