-- AlterTable: track whether a journal day / save was written by the trader (USER)
-- or generated by the daily market-journal cron (LLM). Existing rows are all
-- hand-written, so they default to USER.
ALTER TABLE `trading_journal_entries` ADD COLUMN `author` VARCHAR(8) NOT NULL DEFAULT 'USER';
ALTER TABLE `trading_journal_revisions` ADD COLUMN `author` VARCHAR(8) NOT NULL DEFAULT 'USER';
