-- CreateTable
CREATE TABLE `btc_daytrade_analyses` (
    `id` VARCHAR(191) NOT NULL,
    `date` DATE NOT NULL,
    `direction` VARCHAR(10) NOT NULL,
    `confidence` VARCHAR(10) NULL,
    `entryFrom` DOUBLE NULL,
    `entryTo` DOUBLE NULL,
    `stopLoss` DOUBLE NULL,
    `takeProfitsJson` TEXT NULL,
    `riskReward` DOUBLE NULL,
    `riskPct` DOUBLE NULL,
    `timeframeBiasJson` TEXT NULL,
    `invalidation` TEXT NULL,
    `summary` TEXT NULL,
    `warningsJson` TEXT NULL,
    `analysis` LONGTEXT NOT NULL,
    `reasoning` LONGTEXT NULL,
    `model` VARCHAR(60) NOT NULL,
    `price` DOUBLE NOT NULL,
    `snapshotJson` LONGTEXT NOT NULL,
    `usageJson` TEXT NULL,
    `chartUrl` TEXT NULL,
    `chartObjectKey` VARCHAR(255) NULL,
    `capturedAt` DATETIME(3) NOT NULL,
    `generatedAt` DATETIME(3) NOT NULL,
    `runCount` INTEGER NOT NULL DEFAULT 1,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `btc_daytrade_analyses_date_key`(`date`),
    INDEX `btc_daytrade_analyses_date_idx`(`date` DESC),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
