ALTER TABLE `DailyAnalysis`
  MODIFY `d1Trend`    VARCHAR(191) NULL,
  MODIFY `h4Trend`    VARCHAR(191) NULL,
  MODIFY `d1S1`       DOUBLE NULL,
  MODIFY `d1S2`       DOUBLE NULL,
  MODIFY `d1R1`       DOUBLE NULL,
  MODIFY `d1R2`       DOUBLE NULL,
  MODIFY `h4S1`       DOUBLE NULL,
  MODIFY `h4S2`       DOUBLE NULL,
  MODIFY `h4R1`       DOUBLE NULL,
  MODIFY `h4R2`       DOUBLE NULL,
  MODIFY `llmProvider` VARCHAR(191) NULL,
  MODIFY `llmModel`   VARCHAR(191) NULL;
